cinchapi/concourse

concourse-shell/src/main/java/org/cinchapi/concourse/shell/ConcourseShell.java
I thought about the approach suggested to use a security manager and restrict access to the concourse connection metadata , however it would be rather simple to just restrict the end user to execute a command which tries to use reflection and get access to the private fields of the concourse client. So I added it to the list of banned commands and so the user won't be able to execute it.
=> CON-59: Restrict access to Concourse connection info via reflection

CHANGELOG.md, concourse-integration-tests/src/test/java/org/cinchapi/concourse/TransactionIsolationTest.java, concourse-server/src/main/java/org/cinchapi/concourse/server/storage/AtomicOperation.java, concourse-server/src/test/java/org/cinchapi/concourse/server/storage/EngineAtomicOperationTest.java
Historical reads by definition don't grab locks but if the timestamp was set to the future there was a possibility of a Phantom Read phenomenon.
=> CON-259: Fix historical reads in the future

concourse-server/src/main/java/com/cinchapi/concourse/server/ConcourseServer.java
@jtnelson  I have replaced ```newLinkedHashMap``` with ```TMaps.newLinkedHashMapWithCapacity``` wherever possible to optimize the size of the collection. Please have a look at it and let me know of any issues you find.
P.S- There are no building errors with ```./utils/install-snapshot.sh```
=> Specify size of collections, where possible, in Concourse Server #114

concourse-driver-java/src/main/java/com/cinchapi/concourse/Concourse.java, concourse-ete-test-core/src/main/java/com/cinchapi/concourse/server/ManagedConcourseServer.java, concourse-integration-tests/src/test/java/com/cinchapi/concourse/LinksToTest.java, concourse-integration-tests/src/test/java/com/cinchapi/concourse/OperatorAliasTest.java, concourse-integration-tests/src/test/java/com/cinchapi/concourse/ReferentialIntegrityTest.java
The parameters for the two 'link' methods and 'unlink' method in the class Concourse were changed from (key, source, destination) to (key, destination, source). This was done to match the parameter order of (key, value, record) for the add, set, and remove methods and thus make the parameter order more intuitive. All usages were modified to adjust for this change.
=> GH-115: Changed the parameter order for 'link' and 'unlink' method

concourse-driver-php/src/Concourse.php, concourse-driver-python/concourse/concourse.py, concourse-driver-ruby/lib/concourse/client.rb
Updated the documentation blocks in the Ruby, PHP, and Python drivers to match the parameter order for the link and unlink methods in the Concourse class of the Java driver. Related to GH-115
=> CON-470: Update param order in driver docs as per GH-115

concourse-server/src/main/java/com/cinchapi/concourse/server/storage/Engine.java, concourse-server/src/test/java/com/cinchapi/concourse/server/storage/EngineTest.java
The browse() method in the Engine class was removed and all usages were replaced by the getAllRecords() method from the Store interface.
=> CON-471: Removed Engine#browse() method

concourse-plugin-core/src/main/java/com/cinchapi/concourse/plugin/data/Dataset.java, concourse-plugin-core/src/main/java/com/cinchapi/concourse/plugin/data/DatasetEntry.java, concourse-plugin-core/src/main/java/com/cinchapi/concourse/plugin/data/entry/DatasetEntry.java, concourse-plugin-core/src/test/java/com/cinchapi/concourse/plugin/data/DatasetTest.java
In order for parts of the key-derivation to be detached from the process of updating the `Dataset`, I created a container that is instantiated by these parts and then passed back to the main `ImpromptuApplication` which takes care of entering them into the `Dataset`. Unit Tests are included.
=> Created DatasetEntry class for encapsulating entries for the Dataset

concourse-plugin-core/src/main/java/com/cinchapi/concourse/plugin/data/ResultDataset.java, concourse-plugin-core/src/test/java/com/cinchapi/concourse/plugin/data/DatasetTest.java, concourse-plugin-core/src/test/java/com/cinchapi/concourse/plugin/data/TrackingMultimapDataTypeTest.java, concourse-server/src/main/java/com/cinchapi/concourse/server/ConcourseServer.java, concourse-server/src/main/java/com/cinchapi/concourse/server/GlobalState.java
I changed the `ResultDataset` class to be type parameterized. This is because, by default, `ResultDataset` extended `Dataset<Long, String, Object>`, which made it incompatible to cast to a `Map<Long, Map<String, Set<TObject>>>`. By type parameterizing, this can be specified. If I were to explicitly specify that `ResultDataset` extended `Dataset<Long, String, TObject>`, the problem would be solved for `ConcourseServer` but there would then be incompatibilities with unit testing for the visualization engine and impromptu which use Objects instead of TObjects. This solution therefore maintains backwards compatibility.
Since `RemoteInvocationThread` is a package-friendly class, I was unable to call `instanceof` and instead used `Reflection.getCastedClass(String className)` to get the …
=> [CON-496]  Concourse / Task CON-496 Return Dataset from ConcourseServer select methods that return Map<Long, Map<String, Set<TObject>>>

concourse-plugin-core/src/main/java/com/cinchapi/concourse/server/plugin/data/ObjectResultDataset.java
Just for convenience, so that instantiation does not require the clunky notation:
```java
Dataset<Long, String, Object> dataset = new ObjectResultDataset(new TObjectResultDataset());
```
and can instead be
```java
Dataset<Long, String, Object> dataset = new ObjectResultDataset();
```
=> (CON-555) Making default constructor public so that ObjectResultDataset can be constructed easily

concourse-server/src/main/java/com/cinchapi/concourse/server/cli/core/ManagementCli.java
This commit adds logic to ignore a SecurityException being raised in the
exit method of a ManagementCli. The exception happens because the token
that was being using in the CLI has become invalid. It is safe to ignore
the token on exit because the work that requires authorization has already
been completed.
=> CON-590: Ignore SecurityException thrown on ManagementCli exit

CHANGELOG.md, concourse-ete-test-core/src/main/java/com/cinchapi/concourse/server/ManagedConcourseServer.java, concourse-ete-test-core/src/test/java/com/cinchapi/concourse/server/ManagedConcourseServerInstallTest.java
This commit adds more intelligent that will only forcibly kill the process in older versions of Concourse that don't support the skip-integration flag
=> CON-442: Add robust logic to ensure ManagedConcourseServer is installed across versions without hanging

README.md
The current documentation links are broken. Until the official documentation website is updated/fixed, it makes sense to at least link directly to the documentation that’s automatically deployed during the builds.
=> Updated the README with working documentation links.

CHANGELOG.md, concourse-server/src/main/java/com/cinchapi/concourse/server/upgrade/UpgradeTask.java, concourse-server/src/main/java/com/cinchapi/concourse/server/upgrade/UpgradeTasks.java
This fixes a bug that occurs when a fresh install with upgrade tasks is pointed to an data directory with existing data at an older system version. Previously, the bootstrap process set the system version across the buffer, db and home with the latest system version (without running the upgrade tasks). This fix adjusts the bootstrap process to only set the home system version if it detects that the install is fresh
=> Fix corner case with bootstrapping system version

CHANGELOG.md, concourse-integration-tests/src/test/java/com/cinchapi/concourse/shell/ConcourseShellTest.java, concourse-shell/build.gradle, concourse-shell/src/main/java/com/cinchapi/concourse/shell/ConcourseShell.java
…t syntax within statements containing an open parenthesis
=> GH-463: Fixed a bug that caused Concourse Shell to fail to parse some short syntax

CHANGELOG.md, concourse-integration-tests/src/test/java/com/cinchapi/concourse/CclFunctionsTest.java, concourse-server/src/main/java/com/cinchapi/concourse/server/ConcourseServer.java, concourse-server/src/main/java/com/cinchapi/concourse/server/ops/Operations.java
…`min` function over an entire index as an operation value in a CCL statement.
=> Fixed a bug with min/max calculations of an index as a CCL operation value

CHANGELOG.md, concourse-integration-tests/src/test/java/com/cinchapi/concourse/TransactionWorkflowTest.java, concourse-server/src/main/java/com/cinchapi/concourse/server/storage/temp/ToggleQueue.java, concourse-server/src/test/java/com/cinchapi/concourse/server/storage/temp/ToggleQueueTest.java
Fixed a bug that caused Concourse Server to incorrectly detect when an attempt was made to atomically commit multiple Writes that toggle the state of a field (e.g. `ADD name as jeff in 1`, `REMOVE name as jeff in 1`, `ADD name as jeff in 1`) in user-defined `transactions`. As a result of this bug, all field toggling Writes were committed instead of the desired behaviour where there was a commit of at most one equal Write that was required to obtain the intended field state. Committing multiple writes that toggled the field state within the same transaction could cause failures, unexplained results or fatal inconsistencies when reconciling data.
=> Fix user defined transaction write toggling

CHANGELOG.md, concourse-server/src/main/java/com/cinchapi/concourse/server/io/ByteableCollectionStreamIterator.java, concourse-server/src/test/java/com/cinchapi/concourse/server/io/ByteableCollectionsTest.java
Switched from using memory mapped files in favor of traditional buffering when reading data from Segment files. This change avoids a potential issue where Concourse Server could very quickly exceeded the maximum number of mappings allowed on some Linux systems (as specified by the `vm.max_map_count` property).
=> Use traditional buffer instead of memory mapped files when reading from database files

CHANGELOG.md, concourse-server/src/main/java/com/cinchapi/concourse/server/storage/WriteStreamProfiler.java, concourse-server/src/test/java/com/cinchapi/concourse/server/storage/db/DatabaseTest.java
Fixed a bug in the way that Concourse Server determined if duplicate data existed in the v3 storage files, which caused the `concourse data repair` CLI to no longer work properly (compared to how it worked on the v2 storage files).
=> Fix v3 storage format duplicate data detection

CHANGELOG.md, concourse-server/src/main/java/com/cinchapi/concourse/server/model/Value.java
Fixed a regression that caused a memory leak when data values were read from disk. The nature of the memory leak caused a degradation in performance because Concourse Server was forced to evict cached records from memory more frequently than in previous versions.
=> Fix memory leak when reading Values from disk

CHANGELOG.md, concourse-integration-tests/src/test/java/com/cinchapi/concourse/ReadRecordIdentifierTest.java, concourse-server/src/main/java/com/cinchapi/concourse/server/ops/Stores.java
…as both a selection and evaluation key. The record identifier can be refernced using the `$id$` key (NOTE: this must be properly escaped in `concourse shell` as `\$id\$`).
* It is useful to include the Record identifier as a selection key for some navigation reads (e.g., `select(["partner.name", parner.\$id\$], 1)`)).
* It is useful to include the Record identifier as an evaluation key in cases where you want to explictly exclude a record from matching a `Condition` (e.g., `select(["partner.name", parner.\$id\$], "\$id\$ != 2")`))
=> Added support for querying on Record ids

concourse-server/src/main/java/com/cinchapi/concourse/server/concurrent/LockBroker.java, concourse-server/src/main/java/com/cinchapi/concourse/server/model/Ranges.java, concourse-server/src/test/java/com/cinchapi/concourse/server/concurrent/LockBrokerTest.java, concourse-server/src/test/java/com/cinchapi/concourse/server/model/RangesTest.java
GC locked ranges in LockBroker so performance doesn't degrade over time and also be more intelligent about when to check every locked range for blocking
=> Fix significant write performance regression

CHANGELOG.md, concourse-driver-java/src/main/java/com/cinchapi/concourse/validate/Keys.java
ConcourseServer has to often check if keys are writable or are navigation keys, etc to faciliate writes and real world navigable reads. Previously we cached known writable keys, but we still paid a penalty for navigation keys that were repeatedly both checked againist the WRITABLE_KEY regex and then tokenized. If we were selecting multiple navigation keys for multiple records these keys went through the same validation logic EVERY SINGLE TIME. This update just caches the results of Key parsing and defers all method paths to use Key parsing so checks are more efficient in real world scenarios
=> Cache parsed keys for better performance in reads and writes
